# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_data": "00_core.ipynb",
         "DATAPATH": "00_core.ipynb",
         "DATA_FILES": "00_core.ipynb",
         "data": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/restaurants_timeseries/"

git_url = "https://github.com/fastai/restaurants_timeseries/tree/master/"

def custom_doc_links(name): return None
