# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_data": "00_core.ipynb",
         "DATAPATH": "00_core.ipynb",
         "DATA_FILES": "00_core.ipynb",
         "data": "00_core.ipynb",
         "Logger": "01_view_data.ipynb",
         "logger": "01_view_data.ipynb",
         "get_earliest_date": "01_view_data.ipynb",
         "get_latest_date": "01_view_data.ipynb",
         "VisitsSurveyor": "01_view_data.ipynb",
         "N_MOST_OPEN": "01_view_data.ipynb",
         "N_LEAST_OPEN": "01_view_data.ipynb",
         "vs": "01_view_data.ipynb",
         "most_open_stores": "01_view_data.ipynb",
         "least_open_stores": "01_view_data.ipynb"}

modules = ["core.py",
           "surveyors.py"]

doc_url = "https://fastai.github.io/restaurants_timeseries/"

git_url = "https://github.com/fastai/restaurants_timeseries/tree/master/"

def custom_doc_links(name): return None
