# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['read_data', 'DATAPATH', 'DATA_FILES', 'data']

# Cell
import os
import pandas as pd
DATAPATH = 'data'

DATA_FILES = {
    "simple_visits": os.path.join(DATAPATH, "air_visit_data.csv"),
    "store_info": os.path.join(DATAPATH, "air_store_info.csv"),
    "reservations": os.path.join(DATAPATH, "air_reserve.csv"),
    "date_info": os.path.join(DATAPATH, "date_info.csv")
}

def read_data():
    data = dict([(name, pd.read_csv(path)) for name, path in DATA_FILES.items()])
    stores = data['store_info'].drop_duplicates()
    stores['joinkey']= 'k'
    data['date_info']['joinkey'] = 'k'
    data['all_stores_dates'] = (
        stores
        .merge(data['date_info'], on='joinkey')
        .drop('joinkey', axis=1)
        .rename({'calendar_date': 'visit_date'}, axis=1))
    data['visits'] = (
        data['all_stores_dates']
        .merge(data['simple_visits'], on=['air_store_id', 'visit_date'], how='left'))
    for entry in ('simple_visits', 'all_stores_dates', 'store_info', 'date_info'):
        del(data[entry])
    data['visits'].visitors = data['visits'].visitors.fillna(0).astype(int)
    return data

#export
data = read_data()