# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_data": "f00_core.ipynb",
         "DATAPATH": "f00_core.ipynb",
         "DATA_FILES": "f00_core.ipynb",
         "data": "f00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
