# AUTOGENERATED! DO NOT EDIT! File to edit: f00_core.ipynb (unless otherwise specified).

__all__ = ['read_data', 'DATAPATH', 'DATA_FILES', 'data']

# Cell
DATAPATH = 'data'

DATA_FILES = {
    "visits": os.path.join(DATAPATH, "air_visit_data.csv"),
    "store_info": os.path.join(DATAPATH, "air_store_info.csv"),
    "reservations": os.path.join(DATAPATH, "air_reserve.csv"),
    "date_info": os.path.join(DATAPATH, "date_info.csv")
}

#export
def read_data():
    return dict([(name, pd.read_csv(path)) for name, path in DATA_FILES.items()])

# Cell
data = read_data()